# Generated by Django 4.2.7 on 2025-09-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the template",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject or notification title", max_length=200
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Template content (can use Django template syntax)"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="email",
                        help_text="Type of notification this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable email notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable SMS notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable push notifications"
                    ),
                ),
                (
                    "in_app_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable in-app notifications"
                    ),
                ),
                (
                    "project_updates",
                    models.BooleanField(
                        default=True, help_text="Receive project update notifications"
                    ),
                ),
                (
                    "quote_updates",
                    models.BooleanField(
                        default=True, help_text="Receive quote update notifications"
                    ),
                ),
                (
                    "payment_reminders",
                    models.BooleanField(
                        default=True, help_text="Receive payment reminder notifications"
                    ),
                ),
                (
                    "system_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive system alert notifications"
                    ),
                ),
                (
                    "marketing",
                    models.BooleanField(
                        default=True, help_text="Receive marketing notifications"
                    ),
                ),
                (
                    "do_not_disturb",
                    models.BooleanField(
                        default=False, help_text="Pause all notifications"
                    ),
                ),
                (
                    "do_not_disturb_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Pause notifications until this time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Preference",
                "verbose_name_plural": "User Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Notification subject or title", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="in_app",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        help_text="Current status of the notification",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level of the notification",
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "template_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data used to render the template",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was sent",
                        null=True,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used to generate this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_e285de_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="notificatio_content_702c56_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
