# Generated by Django 4.2.7 on 2025-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                (
                    "currency_code",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency code"
                    ),
                ),
                (
                    "cost_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier applied to plan base prices to estimate local costs",
                        max_digits=6,
                        verbose_name="base cost multiplier",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="timezone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "region",
                "verbose_name_plural": "regions",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["country", "name"],
                        name="locations_r_country_eddb74_idx",
                    )
                ],
            },
        ),
    ]
