# Generated by Django 5.1.13 on 2026-01-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="capital",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="capital city"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="ghana_region_name",
            field=models.CharField(
                blank=True,
                help_text="Official Ghana region name if applicable",
                max_length=50,
                verbose_name="Ghana region name",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="local_materials_available",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of locally available construction materials",
                verbose_name="local materials available",
            ),
        ),
    ]
