# Generated by hand to add quote chat models.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteMessageAttachment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('file', models.FileField(upload_to='quotes/chat/%Y/%m/%d', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quote_chat_attachments',
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='uploaded by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quote message attachment',
                'verbose_name_plural': 'quote message attachments',
            },
        ),
        migrations.CreateModel(
            name='QuoteChatMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('body', models.TextField(verbose_name='message body')),
                ('metadata', models.JSONField(default=dict, blank=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                (
                    'quote',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_messages',
                        to='quotes.quote',
                        verbose_name='quote',
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sent_quote_messages',
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='sender',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quote chat message',
                'verbose_name_plural': 'quote chat messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=timezone.now, verbose_name='read at')),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='receipts',
                        to='quotes.quotechatmessage',
                        verbose_name='message',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quote_message_receipts',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quote message receipt',
                'verbose_name_plural': 'quote message receipts',
                'ordering': ('-read_at',),
            },
        ),
        migrations.AddField(
            model_name='quotechatmessage',
            name='attachments',
            field=models.ManyToManyField(
                blank=True,
                related_name='messages',
                to='quotes.quotemessageattachment',
                verbose_name='attachments',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='quotemessagereceipt',
            unique_together={('message', 'user')},
        ),
    ]
