# Generated by Django 5.2.9 on 2026-01-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_consolidate_quote_systems"),
        ("quotes", "0002_quote_chat"),
    ]

    operations = []
