# Generated by Django 5.2.9 on 2026-01-02 07:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0002_remove_quote_models"),
        ("locations", "0003_migrate_ghana_region_data"),
        ("plans", "0003_alter_planregionalpricing_options_and_more"),
        ("quotes", "0004_make_build_request_nullable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quote",
            name="quote_type_consistency",
        ),
        migrations.AlterField(
            model_name="quote",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="discount amount",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="parent_quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="quotes.quote",
                verbose_name="parent quote",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote_type",
            field=models.CharField(
                choices=[
                    ("BUILD_REQUEST", "Build Request Quote"),
                    ("CONSTRUCTION_PROJECT", "Construction Project Quote"),
                ],
                default="BUILD_REQUEST",
                max_length=20,
                verbose_name="quote type",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="tax amount",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="version"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["construction_request", "status"],
                name="quotes_quot_constru_d770b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_type", "status"], name="quotes_quot_quote_t_f61901_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("build_request__isnull", False),
                        ("construction_request__isnull", True),
                        ("quote_type", "BUILD_REQUEST"),
                    ),
                    models.Q(
                        ("build_request__isnull", True),
                        ("construction_request__isnull", False),
                        ("quote_type", "CONSTRUCTION_PROJECT"),
                    ),
                    _connector="OR",
                ),
                name="quote_type_consistency",
            ),
        ),
    ]
