# Generated by Django 5.1.13 on 2026-01-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyEcoFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "eco_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_eco_features",
                        to="construction.ecofeature",
                        verbose_name="eco feature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_eco_features",
                        to="properties.property",
                        verbose_name="property",
                    ),
                ),
            ],
            options={
                "verbose_name": "property eco feature",
                "verbose_name_plural": "property eco features",
                "unique_together": {("property", "eco_feature")},
            },
        ),
    ]
