# Generated by Django 5.1.13 on 2026-01-01 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_migrate_eco_features_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="eco_features",
        ),
    ]
