# Generated by Django 5.2.11 on 2026-02-15 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_sustainability_field_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("rent", "Rent"), ("lease", "Lease"), ("buy", "Buy")],
                        max_length=10,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("negotiating", "Negotiating"),
                            ("contract_pending", "Contract Pending"),
                            ("contract_signed", "Contract Signed"),
                            ("payment_pending", "Payment Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=200, verbose_name="contact name"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="contact email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=50, verbose_name="contact phone"),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Client's proposed price (for buy) or offer",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="proposed price",
                    ),
                ),
                (
                    "proposed_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Client's proposed monthly rent (for rent/lease)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="proposed rent",
                    ),
                ),
                (
                    "lease_duration_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Desired lease duration in months",
                        null=True,
                        verbose_name="lease duration (months)",
                    ),
                ),
                (
                    "move_in_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="desired move-in date"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Additional message or requirements from the client",
                        verbose_name="message",
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        help_text="Client's budget range",
                        max_length=100,
                        verbose_name="budget",
                    ),
                ),
                (
                    "financing_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether client needs financing assistance (for buy)",
                        verbose_name="financing required",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from admin/agent",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "property_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="properties.property",
                        verbose_name="property",
                    ),
                ),
            ],
            options={
                "verbose_name": "property transaction",
                "verbose_name_plural": "property transactions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TransactionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID", "Identification"),
                            ("PROOF_OF_INCOME", "Proof of Income"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("REFERENCE", "Reference Letter"),
                            ("CONTRACT", "Contract"),
                            ("AGREEMENT", "Agreement"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                        verbose_name="document type",
                    ),
                ),
                ("file_url", models.URLField(verbose_name="file URL")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.propertytransaction",
                        verbose_name="transaction",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_transaction_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction document",
                "verbose_name_plural": "transaction documents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TransactionNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal notes visible only to staff",
                        verbose_name="is internal",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="properties.propertytransaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction note",
                "verbose_name_plural": "transaction notes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="propertytransaction",
            index=models.Index(
                fields=["client", "status"], name="properties__client__41b943_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertytransaction",
            index=models.Index(
                fields=["property_ref", "transaction_type"],
                name="properties__propert_a981d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertytransaction",
            index=models.Index(
                fields=["assigned_agent", "status"],
                name="properties__assigne_624b43_idx",
            ),
        ),
    ]
