# Generated by Django 5.2.11 on 2026-02-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_propertytransaction_transactiondocument_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="propertytransaction",
            new_name="properties__propert_0842ae_idx",
            old_name="properties__propert_a981d5_idx",
        ),
        migrations.AlterField(
            model_name="propertytransaction",
            name="property_ref",
            field=models.ForeignKey(
                db_column="property_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="properties.property",
                verbose_name="property",
            ),
        ),
    ]
