# Generated by Django 5.2.9 on 2026-01-08 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("construction", "0002_remove_quote_models"),
        ("properties", "0005_sustainability_field_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_base_url", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for no maximum",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_loan_term",
                    models.PositiveIntegerField(
                        help_text="Minimum loan term in months"
                    ),
                ),
                (
                    "max_loan_term",
                    models.PositiveIntegerField(
                        help_text="Maximum loan term in months"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "down_payment_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(help_text="Loan term in months"),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annually", "Semi-Annually"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ROICalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("initial_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "annual_savings",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated annual savings in utility costs",
                        max_digits=12,
                    ),
                ),
                (
                    "lifespan_years",
                    models.PositiveIntegerField(
                        help_text="Expected lifespan of the feature in years"
                    ),
                ),
                (
                    "maintenance_cost_per_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual maintenance cost",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GovernmentIncentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "incentive_type",
                    models.CharField(
                        choices=[
                            ("tax_credit", "Tax Credit"),
                            ("grant", "Grant"),
                            ("rebate", "Rebate"),
                            ("loan", "Low-Interest Loan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed amount or percentage (use decimal, e.g., 0.05 for 5%)",
                        max_digits=12,
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="Is the amount a percentage? If not, it's a fixed amount",
                    ),
                ),
                (
                    "min_qualifying_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_qualifying_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_property_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of property types that qualify (e.g., ['APARTMENT', 'HOUSE'])",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("application_url", models.URLField(blank=True)),
                ("documentation_required", models.TextField(blank=True)),
                (
                    "eligible_eco_features",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Eco features that qualify for this incentive",
                        to="construction.ecofeature",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=12)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_interest",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.paymentplan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.project",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
