# Generated by Django 4.2.7 on 2025-10-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0002_plan_publish_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planregionalpricing",
            options={
                "verbose_name": "regional pricing",
                "verbose_name_plural": "regional pricing",
            },
        ),
        migrations.AddField(
            model_name="planfeature",
            name="price_delta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional cost when this option is selected",
                max_digits=10,
                verbose_name="price delta",
            ),
        ),
        migrations.CreateModel(
            name="PlanAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("publish", "Publish"),
                            ("unpublish", "Unpublish"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField(default=dict, verbose_name="changes")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="plans.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "plan audit log",
                "verbose_name_plural": "plan audit logs",
                "ordering": ("-timestamp",),
            },
        ),
    ]
