name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Frontend lint & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: green-tech-africa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: green-tech-africa/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  backend:
    name: Backend lint & tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    env:
      DJANGO_SECRET_KEY: test-secret-key
      DJANGO_DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_CORS_ALLOWED_ORIGINS: http://localhost:5173
      DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost:5173
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_URL: redis://localhost:6379/0
    defaults:
      run:
        working-directory: green_tech_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: flake8 core

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Test
        run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest
